name: Test C Code

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Code 
      uses: actions/checkout@v4

    - name: Setup GCC
      run: sudo apt-get install -y build-essential make

    - name: Run Tests
      run: make test
